{% set version = "1.3" %}

package:
  name: libunistring
  version: {{ version }}

source:
  url: https://ftpmirror.gnu.org/gnu/libunistring/libunistring-{{ version }}.tar.gz
  sha256: 8ea8ccf86c09dd801c8cac19878e804e54f707cf69884371130d20bde68386b7

build:
  number: 0
  skip: True  # [win]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=libunistring
    - {{ pin_subpackage('libunistring', min_pin='x', max_pin='x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
  host:

test:
  commands:
    - test -f $PREFIX/lib/libunistring.so     # [linux]
    - test -f $PREFIX/lib/libunistring.dylib  # [osx]
    - test ! -f $PREFIX/lib/libunistring.a    # [unix]

about:
  home: https://www.gnu.org/software/libunistring
  license: GPL-3.0-only OR LGPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LIB
  summary: This library provides functions for manipulating Unicode strings and for manipulating C strings according to the Unicode standard.
  dev_url: https://savannah.gnu.org/projects/libunistring

extra:
  recipe-maintainers:
    - stefan-balke
    - bgruening
